version: '3.7'

services:
  api:
    container_name: API
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    networks:
      - docker_network
    depends_on:
      - db

  db:
    container_name: BD
    image: postgres:13-alpine
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge

volumes:
  api_db_data:
